# This is the source package for all 4 stages of the pipeline

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
# .sSSSSs.    .sSSSSs.    .sSSSSs.                                  SSSSS .sSSSsSS SSsSSSSS .sSSSSs.    .sSSSSs.    .sSSSSs.                                  .sSSSSSSSs. .sSSSSs.    .sSSS       s.         .sSSSSSSSSSSSSSs. .sSSSSs.    .sSSS SSSSS .sSSSSSSSSSSSSSs.                               .sSSSSs.    .sSSSSSSSs. .sSSSSs.    .sSSSSs.    .sSSSSs.    .sSSSSSSSs. .sSSSSSSSs. .sSSSSs.    .sSSSSs.                                  .sSSSSSSSs. .sSSSSs.    .sSSSSs.    .sSSSSs.    .sSSSSs.    .sSSS SSSSS      
# S SSSSSSSs. S SSSSSSSs. S SSSSSSSs.                               S SSS S SSS  SSS  SSSSS S SSSSSSSs. S SSSSSSSs. S SSSSSSSs.                               S SSS SSSSS S SSSSSSSs. S SSS       SSSs.      SSSSS S SSS SSSSS S SSSSSSSs. S SSS SSSSS SSSSS S SSS SSSSS                               S SSSSSSSs. S SSS SSSSS S SSSSSSSs. S SSSSSSSs. S SSSSSSSs. S SSS SSSS' S SSS SSSS' S SSSSSSSs. S SSSSSSSs.                               S SSS SSSS' S SSSSSSSs. S SSSSSSSs. S SSSSSSSs. S SSSSSSSs. S SSS SSSSS      
# S  SS SSSSS S  SS SSSSS S  SS SSSS'                     Ss.       S  SS S  SS   S   SSSSS S  SS SSSSS S  SS SSSS' S  SS SSSS'                     Ss.       S  SS SSSS' S  SS SSSSS S  SS       SSSSS      SSSSS S  SS SSSSS S  SS SSSS' S  SS SSSSS SSSSS S  SS SSSSS                     Ss.       S  SS SSSSS S  SS SSSS' S  SS SSSSS S  SS SSSS' S  SS SSSS' S  SS       S  SS       S  SS SSSS' S  SS SSSSS                     Ss.       S  SS       S  SS SSSSS S  SS SSSS' S  SS SSSS' S  SS SSSS' S  SS SSSSS      
# S..SS SSSSS S..SS SSSSS S..SS            sssssss sssssssSSSS      S..SS S..SS       SSSSS S..SSsSSSSS S..SS       S..SS            sssssss sssssssSSSS      S..SSsSSSa. S..SSsSSSSS S..SS       SSSSS      `:S:' S..SS `:S:' S..SS       `..SSsSSSs' `:S:' S..SS `:S:'      sssssss sssssssSSSS      S..SS SSSSS S..SSsSSSa. S..SS SSSSS S..SS       S..SS       `SSSSsSSSa. `SSSSsSSSa. S..SS       S..SS SSSSS      sssssss sssssssSSSS      `SSSSsSSSa. S..SS SSSSS S..SS       S..SS       S..SS       S..SSsSSSSS      
# S:::SsSSSSS S:::S SSSSS S:::SSSS                        ;:'       S:::S S:::S       SSSSS S:::S SSSSS S:::S`sSSs. S:::SSSS                        ;:'       S:::S SSSSS S:::S SSSSS S:::S       SSSSS            S:::S       S:::SSSS    s:::S SSSSs       S:::S                           ;:'       S:::SsSSSSS S:::S SSSSS S:::S SSSSS S:::S SSSSS S:::SSSS    .sSSS SSSSS .sSSS SSSSS S:::SSSS    S:::S SSSSS                     ;:'       .sSSS SSSSS S:::SsSSSSS S:::SSSS    S:::SSSS    S:::S SSSSS S:::S SSSSS      
# S;;;S       S;;;S SSSSS S;;;S                                     S;;;S S;;;S       SSSSS S;;;S SSSSS S;;;S SSSSS S;;;S                                     S;;;S SSSSS S;;;S SSSSS S;;;S   S   SSSSS            S;;;S       S;;;S       S;;;S SSSSS       S;;;S                                     S;;;S       S;;;S SSSSS S;;;S SSSSS S;;;S SSSSS S;;;S       S;;;S SSSSS S;;;S SSSSS S;;;S       S;;;S SSSSS                               S;;;S SSSSS S;;;S       S;;;S       S;;;S       S;;;S SSSSS S;;;S SSSSS      
# S%%%S       S%%%S SSSS' S%%%S                                     S%%%S S%%%S       SSSSS S%%%S SSSSS S%%%S SSSSS S%%%S SSSSS                               S%%%S SSSSS S%%%S SSSSS S%%%S  SSS  SSSSS            S%%%S       S%%%S SSSSS S%%%S SSSSS       S%%%S                                     S%%%S       S%%%S SSSSS S%%%S SSSSS S%%%S SSSSS S%%%S SSSSS S%%%S SSSSS S%%%S SSSSS S%%%S SSSSS S%%%S SSSS'                               S%%%S SSSSS S%%%S       S%%%S SSSSS S%%%S SSSSS S%%%S SSSSS S%%%S SSSSS      
# SSSSS       SSSSSsS;:'  SSSSS                                     SSSSS SSSSS       SSSSS SSSSS SSSSS SSSSSsSSSSS SSSSSsSS;:'                               SSSSS SSSSS SSSSS SSSSS SSSSSsSS SSsSSSSS            SSSSS       SSSSSsSS;:' SSSSS SSSSS       SSSSS                                     SSSSS       SSSSS SSSSS SSSSSsSSSSS SSSSSsSSSSS SSSSSsSS;:' SSSSSsSSSSS SSSSSsSSSSS SSSSSsSS;:' SSSSSsS;:'                                SSSSSsSSSSS SSSSS       SSSSSsSS;:' SSSSSsSS;:' SSSSSsSSSSS SSSSS SSSSS      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                      